"""
STREEVA — Area Risk Scoring Engine
app/services/macro_baseline_service.py

NCRB district-level crime baseline service.

Data source:
  National Crime Records Bureau (NCRB) — district-wise IPC crimes
  Original data: data.gov.in / Dataful.in
  Local processed file: data/processed/ncrb_district_lookup.json
  Generated by: scripts/ingest_ncrb.py

How this is used:
  The macro baseline provides city-level historical crime context.
  It is NOT the primary risk signal — it's a prior that shifts the
  baseline up or down relative to national/state average.

  Example: Chennai has 16,861 total IPC crimes (2014), while Ariyalur
  has only 1,615. This context matters: a "safe-looking" location in
  Chennai still carries more baseline risk than the same features in Ariyalur.

Limitations:
  - Data is from 2014 (latest year in dataset.json)
  - NCRB only publishes annual reports — this cannot update live
  - Total IPC crimes include driving offences (rash driving: 8,527 in Chennai)
    which inflates the raw count. We use a curated "violent crime" subset.
  - District-level only — applies uniformly across all H3 cells in Chennai

This is not a flaw — it is the honest design, explicitly documented.
"""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path
from typing import Any

from app.config import get_city_config, get_settings
from app.utils.logger import get_logger

logger = get_logger(__name__)

# Violent crime columns used for baseline (subset of total IPC)
# Rationale: Total IPC includes rash driving (8,527 in Chennai) which
# is a traffic offence, not a violence indicator. We use a curated
# set of offences relevant to personal safety.
VIOLENT_CRIME_FIELDS = [
    "Murder",
    "Attempt to commit Murder",
    "Rape",
    "Attempt to commit Rape",
    "Kidnapping & Abduction_Total",
    "Dacoity",
    "Robbery",
    "Grievous Hurt",
    "Hurt",
    "Acid attack",
    "Assault on Women with intent to outrage her Modesty",
    "Sexual Harassment",
    "Dowry Deaths",
    "Extortion",
    "HumanTrafficking",
]


@lru_cache(maxsize=1)
def _load_district_lookup() -> dict[str, Any]:
    """
    Load the NCRB district lookup JSON from disk.
    Result is cached in memory via lru_cache.

    Returns:
        Dict mapping district name → crime stats.
        Empty dict if file not found (service will use neutral baseline).
    """
    settings = get_settings()
    lookup_path = settings.ncrb_lookup_abs

    if not lookup_path.exists():
        logger.warning(
            "ncrb_lookup_missing",
            path=str(lookup_path),
            hint="Run scripts/ingest_ncrb.py to generate the lookup file.",
        )
        return {}

    try:
        with open(lookup_path, encoding="utf-8") as f:
            data = json.load(f)
        logger.info(
            "ncrb_lookup_loaded",
            path=str(lookup_path),
            district_count=len(data),
        )
        return data
    except Exception as exc:
        logger.error("ncrb_lookup_load_failed", error=str(exc))
        return {}


def get_macro_baseline_score(district: str | None = None, lat: float | None = None, lng: float | None = None) -> tuple[float, dict[str, Any]]:
    """
    Return the macro crime baseline risk score (0–100) for a district.

    Args:
        district: District name matching NCRB data (e.g. 'Chennai').
                  If None, attempts to resolve via lat/lng, then falls back to city config.
        lat: Optional latitude to resolve district.
        lng: Optional longitude to resolve district.

    Returns:
        Tuple of (baseline_score_0_to_100, metadata_dict).
        Returns (50.0, {...}) as neutral baseline if data is unavailable.
    """
    city_config = get_city_config()
    lookup_key = district
    
    if lookup_key is None and lat is not None and lng is not None:
        try:
            from app.services.district_service import get_district_for_location
            resolved_district = get_district_for_location(lat, lng)
            if resolved_district:
                lookup_key = resolved_district
        except Exception as exc:
            logger.error("district_resolution_failed", error=str(exc))
            
    if lookup_key is None:
        lookup_key = city_config.ncrb_district_key

    lookup = _load_district_lookup()

    if not lookup:
        logger.warning("ncrb_using_neutral_baseline", reason="lookup_empty")
        return 50.0, {
            "source": "fallback_neutral",
            "district": lookup_key,
            "reason": "NCRB lookup not available. Run scripts/ingest_ncrb.py.",
        }

    district_data = lookup.get(lookup_key)
    if not district_data:
        # Try case-insensitive match
        lower_key = lookup_key.lower()
        for k, v in lookup.items():
            if k.lower() == lower_key:
                district_data = v
                lookup_key = k
                break

    if not district_data:
        logger.warning("ncrb_district_not_found", district=lookup_key)
        return 50.0, {
            "source": "fallback_neutral",
            "district": lookup_key,
            "reason": f"District '{lookup_key}' not found in NCRB lookup.",
        }

    score = float(district_data.get("normalized_score", 50.0))
    return score, {
        "source": "ncrb_2014",
        "district": lookup_key,
        "violent_crimes": district_data.get("violent_crimes", 0),
        "total_ipc_crimes": district_data.get("total_ipc_crimes", 0),
        "year": district_data.get("year", "2014"),
        "normalized_score": score,
        "state_rank": district_data.get("state_rank"),
        "state_district_count": district_data.get("state_district_count"),
        "note": district_data.get("data_year_note"),
    }
